- hosts: terraform-ansible
  tasks:
  - name: Instalando p python3 e o virtual env
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: Instalando dependencias
    pip:
      virtualenv: /home/ubuntu/teste/venv
      name:
        - django
        - djangorestframework
  - name: Iniciando o projeto
    shell: '. /home/ubuntu/teste/venv/bin/activate; django-admin startproject setup /home/ubuntu/teste/' 
  - name: Alterando o settings
    lineinfile:
      path: /home/ubuntu/teste/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes